# Main application configuration
LogFile = "app.log"

# Enable or disable debug logging for all modules.
Debug = false 

[ai]
# The API Key for the AI service. Can be set directly or via an environment variable.
# Example: APIKey = "${GOOGLE_API_KEY}"
APIKey = "${GOOGLE_API_KEY}"
Model = "gemini-2.5-flash"
ModelTTS = "gemini-2.5-flash-preview-tts"
Voice = "Kore" # Example voices: Kore, Indi, Luma, Fini, Zola, Sol
TranscriptionPrompt = "Please provide a verbatim transcript of the audio."
MainPrompt = """You are a helpful voice assistant.
Based on the transcript, please provide a transcript and concise and accurate response.
Respond in the same language as the transcript.
"""
Thinking = 512 # Dynamic:-1, None:0, low:512, Medium:8192, High:24576
Thoughts = false
EnableTools = true # Set to true to enable tools like Google Search. This may increase response time and cost.

[vad]
# The normalized RMS level below which we consider the audio to be silent.
SilenceThreshold = 0.02
# The amount of time in seconds to continue recording after the audio level drops below the silence threshold.
HangoverDurationSec = 2.0
# Duration to ignore audio at startup to allow the pipeline to stabilize.
# This prevents initial hardware "pops" from triggering a recording.
WarmupDuration = "1500ms"

[recorder]
# Recordings shorter than this (in bytes) will be deleted.
# Example: 600 000 bytes it is mouse click record size.
MinFileSizeBytes = 600000

[display]
# Width of the RMS volume bar in characters.
BarWidth = 100
# How often to refresh the display in milliseconds.
UpdateIntervalMs = 50

[pipeline]
# Physical sound device for input (Default system device by default)
Device = "alsa_output.pci-0000_00_1f.3.analog-stereo.monitor"
# GStreamer source buffer time in microseconds. Helps prevent race conditions.
BufferTimeUs = 500000