# Main application configuration

LogFile = "app.log"

[ai]
Model = "gemini-2.5-flash"
ModelTTS = "gemini-2.5-flash-preview-tts"
Voice = "Kore"
MainPrompt = """
Step 1: Generate a transcript of the speech.
Step 2: Identify the language of the transcript.
Step 3: Respond to the question from the speech in the same language as the transcript.
"""
Thinking = -1 # Dynamic:-1, None:0, low:512, Medium:8192, High:24576
Thoughts = false

[vad]
# The normalized RMS level below which we consider the audio to be silent.
SilenceThreshold = 0.1
# The amount of time in seconds to continue recording after the audio level drops below the silence threshold.
HangoverDurationSec = 2.0

[recorder]
# Recordings shorter than this (in bytes) will be deleted.
MinFileSizeBytes = 1024

[display]
# Width of the RMS volume bar in characters.
BarWidth = 100
# How often to refresh the display in milliseconds.
UpdateIntervalMs = 50

[pipeline]
# Physical sound device for input (Default system device by default)
# Device = "alsa_output.pci-0000_00_1f.3.analog-stereo.monitor"
# GStreamer source buffer time in microseconds. Helps prevent race conditions.
BufferTimeUs = 500000