
name: Develop pipeline

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [opened, synchronize]

jobs:
  call-test-and-build-workflow:
    name: Build and Test
    uses: ./.github/workflows/test-and-build.yaml

  generate-diagrams:
    name: Generate Diagrams
    runs-on: ubuntu-latest
    # This job can run in parallel with test-and-build to save time.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java for PlantUML
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Cache PlantUML jar
        id: cache-plantuml
        uses: actions/cache@v4
        with:
          path: plantuml.jar
          key: ${{ runner.os }}-plantuml-v1.2024.4

      - name: Download PlantUML jar
        if: steps.cache-plantuml.outputs.cache-hit != 'true'
        run: wget -O plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2024.4/plantuml-1.2024.4.jar

      - name: Generate Diagrams from PUML files
        run: java -jar plantuml.jar -tpng UML/

      - name: Upload diagram artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uml-diagrams
          path: UML/*.png