name: Master Pipeline

on:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize]

jobs:
  call-test-and-build-workflow:
    name: Build and Test
    uses: ./.github/workflows/test-and-build.yaml